//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EasyQuestion
    {
        public int eQnID { get; set; }
        public string eQn { get; set; }
        public string eImageName { get; set; }
        public string eOption1 { get; set; }
        public string eOption2 { get; set; }
        public string eOption3 { get; set; }
        public string eOption4 { get; set; }
        public Nullable<int> eAnswer { get; set; }
    }
}
