//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HardQuestion
    {
        public int hQnID { get; set; }
        public string hQn { get; set; }
        public string hImageName { get; set; }
        public string hOption1 { get; set; }
        public string hOption2 { get; set; }
        public string hOption3 { get; set; }
        public string hOption4 { get; set; }
        public Nullable<int> hAnswer { get; set; }
    }
}
