//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegularQuestion
    {
        public int rQnID { get; set; }
        public string rQn { get; set; }
        public string rImageName { get; set; }
        public string rOption1 { get; set; }
        public string rOption2 { get; set; }
        public string rOption3 { get; set; }
        public string rOption4 { get; set; }
        public Nullable<int> rAnswer { get; set; }
    }
}
